import create from 'zustand';

interface usenewArtistStoreType {
  artistList: {
    id: string;
    name: string;
    position: string;
    description: string;
    photo: string[];
  }[];
}

const usenewArtistStore = create<usenewArtistStoreType>((set) => ({
  artistList: [
    {
      id: 'kimseoungsoo',
      name: 'Kim Seungsoo',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimayeong',
      name: 'Kim Ayeong',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4'],
    },
    {
      id: 'parkseyeon',
      name: 'Park Seyeon',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'parku',
      name: 'Park U',
      position: 'Mixture',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'simeunsol',
      name: 'Sim Eunsol',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'leesangyeop',
      name: 'Lee Sangyeop',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'changjinyeong',
      name: 'Chang Jinyeong',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'junghagyeong',
      name: 'Jung Hagyeong',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'choiyeonjae',
      name: 'Choi Yeonjae',
      position: 'Western Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'hwangtak',
      name: 'Hwang Tak',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimseonghun',
      name: 'Kim Seonghun',
      position: 'Acrylic, Oil',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimsojeong',
      name: 'Kim Sojeong',
      position: 'Acrylic, Oil',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimjeongyong',
      name: 'Kim Jeongyong',
      position: 'Ink',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: '',
      name: 'Kim Jihye',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimhyeonju',
      name: 'Kim Hyeonju',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'parkyunjin',
      name: 'Park Yunjin',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'banyeji',
      name: 'Ban Yeji',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'shinyeji',
      name: 'Shin Yeji',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'ohhyejun',
      name: 'Oh Hyejun',
      position: 'Ceramic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'leenayeong',
      name: 'Lee Nayeong',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'leedahye',
      name: 'Lee Dahye',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'chowongyeong',
      name: 'Cho Wongyeong',
      position: 'Maca',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'chunnuni',
      name: 'Chun Nuni',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'choiyeojin',
      name: 'Choi Yeojin',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kasanghyeon',
      name: 'Ka Sanghyeon',
      position: 'Photographer',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kosanghyeon',
      name: 'Ko Sanghyeon',
      position: 'IIstallation Art',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kwonryeonggu',
      name: 'Kwon Ryeonggu',
      position: 'Photographer',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kwonjieun',
      name: 'Kwon Jieun',
      position: 'Oriental Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kwonhyeokeon',
      name: 'Kwon Hyeokeon',
      position: 'Figure Paintin',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'komnaryeong',
      name: 'Kim Naryeong',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimnamu',
      name: 'Kim Namu',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimminju',
      name: 'Kim Minju',
      position: 'Oriental Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimminji',
      name: 'Kim Minji',
      position: 'Abstract Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimminhui',
      name: 'Kim Minhui',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimsijin',
      name: 'Kim Sijin',
      position: 'Abstract Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimayeon',
      name: 'Kim Ayeon',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimjeonga',
      name: 'Kim Jeonga',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimhyojeong',
      name: 'Kim Hyojeong',
      position: 'Pastel',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'namyuri',
      name: 'Nam Yuri',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'laetitia',
      name: 'Laetitia',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'mipak',
      name: 'Mi Pak',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'parkseongho',
      name: 'Park Seongho',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'sungyeonhwa',
      name: 'Sung Yeonhwa',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'shinhyosun',
      name: 'Shin Hyosun',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'yonghahyeon',
      name: 'Yong Hahyeon',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'woohanam',
      name: 'Woo Hanam',
      position: 'Mixture',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'wonhyeri',
      name: 'Won Hyeri',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'yoodaeun',
      name: 'Yoo Daeun',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'leere',
      name: 'Lee Re',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'leesanghwa',
      name: 'Lee Sanghwa',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'leeinhye',
      name: 'Lee Inhye',
      position: 'Sketch',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'leejiseon',
      name: 'Lee Jiseon',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'limjuyeong',
      name: 'Lim Juyeong',
      position: '',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'jangsujin',
      name: 'Jang Sujin',
      position: 'Sculpture',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'chosua',
      name: 'Cho Sua',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'jongu',
      name: 'Jong U',
      position: 'Digital Drawing',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'choigyuri',
      name: 'Choi Gyuri',
      position: 'Mixture',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'choijinyeon',
      name: 'Choi Jinyeon',
      position: 'IIstallation Art',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'huhjeongrok',
      name: 'Huh Jeongrok',
      position: 'Oil Painting',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
    {
      id: 'kimbareu',
      name: 'Kim Bareu',
      position: 'Acrylic',
      description: 'none',
      photo: ['1', '2', '3', '4', '5'],
    },
  ],
}));

export { usenewArtistStore };
